Разметка всех страниц
htmlacademy-htmlcss/2050153-device-34 pull request #1
Opened 2022-07-21 12:25 UTC by NataliZin85

2022-07-22 15:39 UTC, Espanol-nikkol requested changes

2022-07-22 15:39 UTC, Espanol-nikkol commented on catalog.html
> +            alt="Логотип интернет-магазина Девайс">
всем описаниям нужна точка в конце, влияет на скринридер

2022-07-22 15:39 UTC, Espanol-nikkol commented on catalog.html
> +                <button class="navigation-user-button navigation-user-button-get-out" href="#">
кнопке href не нужон

2022-07-22 15:39 UTC, Espanol-nikkol commented on catalog.html
> +                <a class="navigation-menu-link navigation-menu-link-product-catalog" href="catalog.html">Каталог товаров
нельзя в интерактивный элемент вкладывать интерактивный элемент
`Каталог товаров` - не ссылка в принципе. Сбоку от макета написана логика для этого элемента
При таком размещении при наведении на выпадающий элемент будет срабатывать наведение и на `Каталог товаров`, а так не должно быть

2022-07-22 15:39 UTC, Espanol-nikkol commented on styles/styles.css
> +/* .visually-hidden {
а зачем скрывать?

2022-07-22 15:39 UTC, Espanol-nikkol commented on styles/styles.css
> +  opacity: 0.3;
можно просто :disabled { opacity: 0.3; pointer-events: none } тогда никаких событий наведения, фокуса и прочего просто не будет происходить

2022-07-22 15:39 UTC, Espanol-nikkol commented on index.html
> +            <button class="button-icon search-button-icon" type="submit" value="Найти"></button>
если это под иконку лупы - то не надо, она декоративная, это не аналог кнопки сабмита

2022-07-22 15:39 UTC, Espanol-nikkol commented on index.html
> +            <div class="gallery-item gallery-item-drone">
слайдер - это список элементов

2022-07-22 15:39 UTC, Espanol-nikkol commented on index.html
> +              <button class="slider-button slider-prev" type="button">
кнопки переключения не дублируются в каждом слайде

2022-07-22 15:39 UTC, Espanol-nikkol commented on index.html
> +                <span class="visually-hidden">Предыдущее фото</span>
скорее `предыдущий слайд`

2022-07-22 15:39 UTC, Espanol-nikkol commented on index.html
> +                <button class="button information-button information-button-current" type="button">Доставка</button>
тоже самое. Здесь тоже слайдер, значит тоже список. И значит кнопки управления (доставка, каталог, гарантия) не дублируются в каждом слайде

2022-07-27 00:50 UTC, NataliZin85 commented on styles/styles.css
> +/* .visually-hidden {
потомучто я прописала для некоторых вариантов в html visually-hidden. а надо было в CSS прописывать display: none; я переделаю позже

2022-07-27 02:56 UTC, NataliZin85 commented on catalog.html
> +            alt="Логотип интернет-магазина Девайс">
а как влияет?

2022-07-27 03:14 UTC, NataliZin85 commented on catalog.html
> +                <a class="navigation-menu-link navigation-menu-link-product-catalog" href="catalog.html">Каталог товаров
не поняла как прописывать

2022-07-27 03:18 UTC, NataliZin85 commented on styles/styles.css
> +/* .visually-hidden {
С этим я разобралась Просто я думала решить проблему со слайдерами и другими элементами, которые нужно прописывать через отдельный класс .headen. Я их прописала через .visually-headen, потому что ты его не видишь. только забыла Про скурин ридеры...

2022-07-27 03:21 UTC, NataliZin85 commented on index.html
> +            <div class="gallery-item gallery-item-drone">
А почему не подходит div? Я думала - это блоки отдельные?

2022-07-28 13:28 UTC, NataliZin85 commented on index.html
> +              <button class="slider-button slider-prev" type="button">
непоняла почему

2022-07-28 13:29 UTC, NataliZin85 commented on index.html
> +                <button class="button information-button information-button-current" type="button">Доставка</button>
не поняла, не пойму как прописывать

2022-08-24 02:18 UTC, merged